name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repozitoriyni yuklash
        uses: actions/checkout@v4

      - name: Python-ni o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Barcha kerakli kutubxonalarni o'rnatish
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl customtkinter matplotlib pillow pyinstaller

      - name: EXE dasturini barcha modullar bilan yig'ish
        run: |
          pyinstaller --noconsole --onefile --copy-metadata pandas --hidden-import=pandas --hidden-import=openpyxl --hidden-import=PIL --collect-all customtkinter --collect-all pandas --collect-all openpyxl --name="Korrupsiya_Monitoring" main.py

      - name: Tayyor EXE faylni yuklab olish uchun saqlash
        uses: actions/upload-artifact@v4
        with:
          name: Korrupsiya_Monitoring_EXE
          path: dist/Korrupsiya_Monitoring.exe
